### ISSUE TITLE
why there is a 'multiplier' param in the loss funtion?

### ISSUE THREAD

**Issue by luanyunteng** [yuanli2333/Teacher-free-Knowledge-Distillation#6]
As the title says, I do not understand why to multiple the kd loss, and how to set the params?

**Comment by yuanli2333** [comment]
Hi, 
The multipler in regularization loss or kd loss only exist for a few of models/experiments on CIFAR100. We empirically find that for some models on CIFAR100, a stronger regularization is needed, so we use a multiper to enhance the regularzation. Potential reason may be the data distribution of dataset (CIFAR100). We know that the 100 classes in the CIFAR-100 are grouped into 20 superclasses. So many image with different classes are belongs to a "coarse" label (superclasses), which means there are similar in some degree. So the hard labels are not so 'correct', and soft regularization is important. In such scenario,  a stronger regularization can make the model learn more from soft labels (soft regularization) rather than the hard labels. 
But it should be noted that for most of the experiments/models on CIFAR100, there is no multipler (or multipler=1).  There is also no multipler for ImageNet, we will update codes/details for ImageNet.

**Comment by luanyunteng** [comment]
> Hi,
> The multipler in regularization loss or kd loss only exist for a few of models/experiments on CIFAR100. We empirically find that for some models on CIFAR100, a stronger regularization is needed, so we use a multiper to enhance the regularization. Potential reason may be the data distribution of dataset (CIFAR100). We know that the 100 classes in the CIFAR-100 are grouped into 20 superclasses. So many images with different classes are belongs to a "coarse" label (superclasses), which means they are similar in some degree, thus the hard labels are not so 'correct'. In such scenario, a stronger regularization can make the model learn more from soft labels (soft regularization) rather than the hard labels.
> But it should be noted that for most of the experiments/models on CIFAR100, there is no multipler (or multipler=1). There is also no multipler for ImageNet, we will update codes/details for ImageNet.

thanks a lot!
